### ISSUE TITLE
FreeBSD

### ISSUE THREAD

**Issue by sticilface** [igrr/mkspiffs#16]
any chance of modifying the makefile for target : freebsd.. 

I've tried editing it, but I'm hopeless with Makefiles.

:)

**Comment by igrr** [comment]
There's now a case in the Makefile for FreeBSD:
https://github.com/igrr/mkspiffs/blob/dc797c20bf6f68b24cd01f08175d0977d09c985a/Makefile#L22-L24

I've copied it over from esptool-ck, which got FreeBSD case from a recent PR. Since i can't test this myself, please let me know if anything else is needed.
